ALTER TABLE ORDERS ADD FOREIGN KEY (Sno) REFERENCES SALESMEN(Sno) 
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ORDERS ADD FOREIGN KEY (Cno) REFERENCES CUSTOMER(Cno) 
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE SHIPMENT ADD FOREIGN KEY (Ono) REFERENCES ORDERS(Ono)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SHIPMENT ADD FOREIGN KEY (Cno) REFERENCES CUSTOMER(Cno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE SALESMEN ADD FOREIGN KEY (Bno) REFERENCES BRANCH(Bno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE WAREHOUSE ADD FOREIGN KEY (Bno) REFERENCES BRANCH(Bno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Online_account ADD FOREIGN KEY (Cno) REFERENCES CUSTOMER(Cno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PAYMENT ADD FOREIGN KEY (Ono) REFERENCES ORDERS(Ono)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INCLUDE ADD FOREIGN KEY (Ono) REFERENCES ORDERS(Ono)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INCLUDE ADD FOREIGN KEY (Fno) REFERENCES FURNITURE(Fno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PLENISH ADD FOREIGN KEY (Bno) REFERENCES BRANCH(Bno)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PLENISH ADD FOREIGN KEY (Spno) REFERENCES SUPPLIER(Spno)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PLENISH ADD FOREIGN KEY (Fno) REFERENCES FURNITURE(Fno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PURCHASE_PRICE ADD FOREIGN KEY (Spno) REFERENCES SUPPLIER(Spno)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PURCHASE_PRICE ADD FOREIGN KEY (Fno) REFERENCES FURNITURE(Fno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE STORE ADD FOREIGN KEY (Fno) REFERENCES FURNITURE(Fno)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE STORE ADD FOREIGN KEY (Bno) REFERENCES BRANCH(Bno)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CUSTOMER_COUPON ADD FOREIGN KEY (Ono) REFERENCES ORDERS(Ono)
	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CUSTOMER_COUPON ADD FOREIGN KEY (Cno) REFERENCES CUSTOMER(Cno)
	ON DELETE CASCADE ON UPDATE CASCADE;